services:
  php:
    build:
      context: ./php
      dockerfile: php.dockerfile

    volumes:
      - ../backend:/var/www/html

    depends_on:
      - mysql
      - redis

  composer:
    build:
      context: ./composer
      dockerfile: composer.dockerfile

    volumes:
      - ../backend:/var/www/html

    working_dir: /var/www/html

  nginx:
    image: nginx:latest

    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

      - ../backend/public:/var/www/html/public # Подключаем публичную папку Laravel

    depends_on:
      - php
      - redis

  mysql:
    image: mysql:latest

    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
      retries: 3
      timeout: 5s

    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ../
      dockerfile: deployment/frontend/frontend.dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules # node_modules не затирается volume-ом
    working_dir: /app
    command: npm run dev -- --host

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data
  worker:
    build:
      context: ./php
      dockerfile: php.dockerfile

    volumes:
      - ../backend:/var/www/html

    depends_on:
      mysql:
        condition: service_healthy # Ожидаем, пока MySQL не станет здоровым

    # restart: always
    command: php artisan queue:work --verbose --tries=3 --timeout=90
volumes:
  mysql_data:
  redis_data:
